{% set name = "pystardb" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyStarDB-{{ version }}.tar.gz
  sha256: 75a9b52fe59451767492c86622d4ccd19d0d5707083fcc748c28465021ddcea7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.14.5
    - pandas >=1.0.5
    - python >=3.7

test:
  imports:
    - pyStarDB
    - pyStarDB.sp_pystardb
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MPI-Dortmund/pyStarDB
  summary: Star file python Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - mstabrin
    - thorstenwagner
